import { Metadata } from "next";
import Gnb from "@/components/commons/Gnb";
import TapBar from "@/components/commons/TapBar";
import UpcomingStudy from "@/components/domains/mystudy/UpcomingStudy";
import CreateStudyButton from "@/components/commons/CreateStudyButton";
import MyStudyTab from "@/components/domains/mystudy/MyStudyTab";

export const metadata: Metadata = {
  title: "내 스터디",
  description: "Generated by create next app",
};

export default async function Layout({ tabs }: { tabs: React.ReactNode }) {
  return (
    <>
      <Gnb />
      <TapBar />
      <UpcomingStudy />
      <MyStudyTab />
      {tabs}
      <CreateStudyButton />
    </>
  );
}
