import { getSession } from "@/lib/database/getSession";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "스터디 지원서 확인하기",
  description: "Generated by create next app",
};

export default async function layout({ children }: { children: ReactNode }) {
  const session = await getSession();
  const isLoggedIn = !!session;
  if (!isLoggedIn) redirect("/login");
  if (isLoggedIn) return <>{children}</>;
}
