import { Metadata } from "next";
import { getSession } from "@/lib/database/getSession";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "로그인 페이지",
  description: "Generated by create next app",
};

export default async function Layout({ children }: { children: React.ReactNode }) {
  const session = await getSession();
  const isLoggedIn = !!session;
  if (isLoggedIn) redirect("/");
  if (!isLoggedIn) return <>{children}</>;
}
