import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "마이페이지",
  description: "Generated by create next app",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <>{children}</>;
}
