import HorizontalDivider from "@/components/commons/HorizontalDivider";
import TopBar from "@/components/commons/TopBar";
import type { Metadata } from "next";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "my page",
  description: "Generated by create next app",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  const headersList = headers();
  const headerPathname = headersList.get("x-pathname") || "";

  const isMyPage = headerPathname === "/mypage";
  const isProfile = headerPathname.startsWith("/profile");

  return (
    <>
      {(isMyPage || isProfile) && (
        <div className="flex-col inline-flex w-full max-h-dvh">
          <div className="flex-1 overflow-auto scrollbar-hide bg-gradient-to-br from-gradient-gray/30 to-gradient-to/30 ">
            <TopBar variant="chat" showBookmark={isMyPage}>
              {isMyPage && "마이페이지"}
            </TopBar>
            <HorizontalDivider addStyle="opacity-20" />
            {children}
          </div>
        </div>
      )}
      {!(isMyPage || isProfile) && children}
    </>
  );
}
