import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: {
    template: "Sturing | %s",
    default: "Sturing",
  },
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <SessionProvider>
        <body className={`${pretendard.variable} font-pretendard bg-[#f5f5f5] min-w-screen flex flex-col items-center`}>
          <main className="w-screen sm:w-[600px] bg-white min-h-screen shadow-xl relative">{children}</main>
          <div id="modal"></div>
        </body>
      </SessionProvider>
    </html>
  );
}
