import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "프로필 수정",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
