import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Apply",
  description: "Generated by create next app",
};

export default function layout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
